### PR TITLE
Rewrite of duo-ls

### PR DESCRIPTION
**Pull request by dominicbarnes**
All right, I've been wanting to do this for a while, so finally took the time to get it done! I've rewritten `duo-ls` and changed a number of key things about how it operates:

 * dropped the requirement of a `component.json`
 * now works in the context of entry files (like the rest of duo)
 * can now filter out remotes
 * can now output in a machine-friendly format

Under the hood, it now uses the `duo.install()` method (and the fact that it returns the mapping) to determine the output. This means that it also needs any build-level configuration such as plugins in order to successfully run. There is also a "stale" mode, which simply returns the mapping as it exists in the cache, rather than re-resolving the entire build. (also eliminates the need for plugins)

Some examples: (all using [dominicbarnes/slider](https://github.com/dominicbarnes/slider))

```sh
$ duo ls index.js
```

screen shot 2015-07-25 at 10 22 53 pm

Main differences in the output:
 * local files are bold (with the entry file also underlined)
 * local files are also output using the full relative path (before, they were accidentally being output with only the basename)
 * there is a 2 space prefix, which I thought looked nicer with the padding above and below

```sh
$ duo ls index.js --no-remotes
```

screen shot 2015-07-25 at 10 26 58 pm

```sh
$ duo ls index.js --no-remotes --flat
```

screen shot 2015-07-25 at 10 28 18 pm

This particular mode is going to be useful in things like a `Makefile`, in order to automatically construct a list of prerequisites!

```make
build/index.js: component.json $(shell duo-ls index.js --no-remotes --flat)
    duo $<
```

Any feedback is much appreciated. :)

### CODE REVIEW

**Comment by matthewmueller** [comment]
niceee lgtm!

**Comment by dominicbarnes** [comment]
Looks like this feature is gonna have to wait a bit longer. When playing around with this in a few components, I've come across a few problems.

I'm getting "call stack size exceeded" errors on certain components. I'm not sure if there's some circular dependencies or what, but I'll need to investigate further.

The results look confusing when a remote has multiple files. My initial tests all seemed to have components with a single `index.js`, which looks fine. However, with remotes that have multiple files (such as a `lib/` dir) the results look pretty bad. (looks like deps are duplicated)

I _think_ I'll need to construct my tree by chunking entire remotes together, rather than processing each individual file. Either way, hold off on merging this right now.

**Comment by RobLoach** [comment]
Anything going on with this one? Last action was in July.

**Comment by dominicbarnes** [comment]
Yeah, this PR should probably be closed then. It's got issues as I mentioned in the last comment, and I've not had the time to dedicate to finding a fix.

**Pull request closed without merging**
